### ISSUE TITLE
WiiBrowser

### ISSUE THREAD

**Issue by botslayrz** [OpenShopChannel/outdated-apps#103]
### Currently Listed Version

rev132

### URL to new version

https://oscwii.org/library/app/wiibrowser

### Version of Updated App

1

### Select listing type

Apps

### More Information

No.

**Comment by Artuto** [comment]
r132 is the latest version 
![image](https://github.com/OpenShopChannel/outdated-apps/assets/9273973/03ce2066-aa31-4672-9b38-eecadac573ea)

If you have a newer version let us know where.

**Comment by botslayrz** [comment]
No I’m saying the Chanel is in need of updating it doesn’t even load a
website

**Comment by botslayrz** [comment]
Like google

**Comment by GabubuAvailable** [comment]
Bro you pointed the OSCWii.org as the URL to new version. What do you mean...

**Comment by playerjmr** [comment]
> No I’m saying the Chanel is in need of updating it doesn’t even load a website

the purpose of this repository is to report links that are outdated for apps, not for apps to be updated. OSC does not make the apps, it is a repository for apps from other developers.

Wiibrowser doesnt work well because the Wii is not capable of accessing most modern websites due to the https certificates being too new for the Wii.

**Comment by NezbednikSK** [comment]
Is it [this](https://github.com/bastiro03/WiiBrowser-Lite) by any chance?

**Comment by Artuto** [comment]
Not the same, but seems to be a fork:

> WiiBrowser Lite is a homebrew alternative to the Wii's Internet Channel, and it is a revival project of the original WiiBrowser by gave92
