### ISSUE TITLE
USB Loader GX (New Version)

### ISSUE THREAD

**Issue by ghost** [OpenShopChannel/outdated-apps#113]
### Currently Listed Version

3.0 r1281

### URL to new version

https://github.com/wiidev/usbloadergx/releases

### Version of Updated App

3.0 r1281

### Select listing type

Apps

### More Information

The version you have on the Open Shop Channel causes problems with SD card mode. It also causes games to look weird in channel view on Wii U. The new version I linked fixes all of that.

**Comment by Artuto** [comment]
It's the same exact binary.

![image](https://github.com/user-attachments/assets/fdbfe7e6-aa75-4858-ae0d-9683a3a4f1e9)

**Comment by ghost** [comment]
I know they are the same binary, but the current version of ULGx on OSC
still causes issues with SD mode. I don't know why, I don't know how. It
just does.

**Comment by GabubuAvailable** [comment]
And yet we talk about about that. Here's the reason that we covered on Discord server:
![image](https://github.com/user-attachments/assets/c60ad83d-ce20-4084-a1df-7a0f481d3a13)
In short, the XML file have double hypens which breaks the parser.
![image](https://github.com/user-attachments/assets/413e9557-0b24-44eb-ab7d-8ba8d18d366d)

So that means, we have to wait for the developer to find a fix for this. We cannot do anything at this moment...

**Comment by GabubuAvailable** [comment]
In the meantime, you can get the meta.xml file from the official repository of [USB Loader GX](https://github.com/wiidev/usbloadergx/releases) and replace it in your SD card then try again.
