### ISSUE TITLE
WiiBrowser

### ISSUE THREAD

**Issue by GreatBlock4042** [OpenShopChannel/outdated-apps#46]
### Currently Listed Version

rev132

### URL to new version

https://github.com/speediegq/revolutionarchive/releases/tag/rev1

### Version of Updated App

Unknown

### Select listing type

Apps

### More Information

Go to the website and click on:
WiiBrowser.with.FIXED.DOL.wad
Or click here:
https://github.com/speediegq/revolutionarchive/releases/download/rev1/WiiBrowser.with.FIXED.DOL.wad

**Comment by larsenv** [comment]
I downgraded WiiBrowser because someone said that the latest version doesn't connect to websites properly, which didn't seem to be the case. I was having issues connecting to websites on the old and the new version.

To be honest, you can at least browse some of the Internet with the Internet Channel, WiiBrowser works poorly compared to the Internet Channel.
